[package]
name = "dyndns-daemon"
version = "0.1.0"
authors = ["Simon Roosen <simon@firepulse.de>"]

[dependencies]
lettre = "0.6"
error-chain = "*"
chrono = "0.2"
lazy_static = "0.2.2"
iron = "0.5.1"
envy = "0.1.2"
dotenv = "0.8.0"
serde = "0.8.*"
serde_derive = "0.8.*"
slog = { version = "1.2", features = ["max_level_trace", "release_max_level_warn"] }
slog-term = "1.3.5"
clippy = {version = "*", optional = true}

