[package]
name = "dyndns-daemon"
version = "1.0.0"
authors = ["Simon Roosen <simon@firepulse.de>"]

publish = false

readme = "README"

license = "MIT"

[profile.release]
lto = true

[dependencies]
lettre = "0.6"
error-chain = "*"
chrono = "0.2"
lazy_static = "0.2.2"
iron = "0.5.1"
envy = "0.1.2"
dotenv = "0.8.0"
serde = "0.8.*"
serde_derive = "0.8.*"
slog = { version = "1.2", features = ["max_level_trace", "release_max_level_info"] }
slog-term = "1.3.5"
clippy = {version = "*", optional = true}
itertools = "0.5.9"
consistenttime = "0.2.0"

[dev-dependencies]
quickcheck = "0.4.1"
quickcheck_macros = "0.4.1"
